trigger:
- main

pr:
- main

jobs:
- job: PullCode
  pool:
    name: Windows VM  # Replace with the name of your self-hosted agent pool
    demands: msbuild
    vmImage: 'windows-latest'

  steps:
  - checkout: self
    clean: true
    fetchDepth: 1
    displayName: 'Checkout repository'

  - script: |
      # Create the C:\temp folder if it doesn't exist
      New-Item -ItemType Directory -Path C:\temp -Force | Out-Null
      
      # Copy the contents of the repository to C:\temp
      Copy-Item -Path "$(System.DefaultWorkingDirectory)\*" -Destination C:\temp -Recurse -Force
    displayName: 'Copy code to C:\temp'
