trigger:
- master

pr:
- master

jobs:
- job: CopyFilesToWindowsVM
  pool:
    name: 'Windows VM'
    demands: msbuild
    vmImage: 'Windows VM'

  steps:
  - checkout: self
    clean: true
    fetchDepth: 1
    displayName: 'Checkout repository'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Remove existing files in the target folder
        Remove-Item -Path '\\YourWindowsVM\C$\temp\*' -Force -Recurse
    displayName: 'Clean target folder on Windows VM'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**'
      TargetFolder: '\\\\YourWindowsVM\\C$\\temp'  # Note the use of double backslashes
    displayName: 'Copy files to Windows VM'

  - powershell: |
      # Optional: Run additional PowerShell commands on the Windows VM after copying files
      # Example: Invoke-Command -ComputerName YourWindowsVM -ScriptBlock { YourScriptHere } -Credential $env:USERNAME
    displayName: 'Run additional PowerShell commands on Windows VM'
