trigger:
- main

pr:
- main

jobs:
- job: Build
  pool:
    name: 'Windows VM'
    demands: msbuild
    vmImage: 'windows-latest'

  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
    displayName: 'Install .NET Core SDK'

  - script: dotnet restore
    displayName: 'Restore dependencies'

  - script: dotnet build --configuration $(BuildConfiguration)
    displayName: 'Build project'

- job: Deploy
  pool:
    name: 'Windows VM'
    demands: msbuild
    vmImage: 'windows-latest'

  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
    displayName: 'Install .NET Core SDK'

  - script: dotnet publish --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)
    displayName: 'Publish artifacts'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: '<AzureSubscription>'
      appType: 'webApp'
      WebAppName: '<YourWebAppName>'
      packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
      enableCustomDeployment: true
      DeploymentType: 'webDeploy'
