trigger:
- master

pool:
  name: Windows VM

jobs:
- job: PullCode
  displayName: 'Pull Code from Git'
  steps:
  - checkout: self
    clean: true

  - powershell: |
      # Replace <YourGitRepository> with your actual Git repository URL
      $repositoryUrl = "https://github.com/bkeshavrao77/dotnet12.git"
      
      # Replace <YourPersonalAccessToken> with your actual Personal Access Token
      $pat = "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"
      
      # Replace <YourTargetFolder> with your actual target folder path
      $targetFolder = "C:\temp"

      # Clone the repository
      git clone $repositoryUrl

      # Navigate to the repository folder
      cd "$(System.DefaultWorkingDirectory)/dotnet12"

      # Checkout the master branch
      git checkout master

      # Pull the latest code
      git pull origin master

      # Copy the code to the target folder
      Copy-Item -Path .\* -Destination $targetFolder -Recurse -Force
    env:
      GIT_TERMINAL_PROMPT: 0
    displayName: 'Pull Code and Copy to Target Folder'
