trigger:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'C:\test\HelloWorldApp'
- main
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

pr:
- main

jobs:
- job: Build
  pool:
    name: 'Windows VM'
    demands: msbuild
    

  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
    displayName: 'Install .NET Core SDK'

 - script: 
    echo Current Directory: $(System.DefaultWorkingDirectory)
  displayName: 'Print Current Directory'


 - script: dotnet build --configuration $(BuildConfiguration) --project YourProjectFile.csproj
  displayName: 'Build project'

- script: 
    dir
  displayName: 'List Files in Current Directory'

- job: Deploy
  pool:
    name: 'Windows VM'
    demands: msbuild
    vmImage: 'windows-latest'

