trigger:
- master

pr:
- master

jobs:
- job: StopIISOnWindowsVM
  pool:
    vmImage: 'Windows VM'

  steps:
  - checkout: self
    clean: true
    fetchDepth: 1
    displayName: 'Checkout repository'

  - task: IISWebAppManagementOnMachineGroup@0
    inputs:
      action: 'Stop'
      servers: '$(7AK7F0)'  # Replace with your Windows VM computer name
    displayName: 'Stop IIS on Windows VM'
